name: Build Cronix

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6 PyQt6-WebEngine

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --collect-all PyQt6 --collect-all PyQt6-WebEngine --hidden-import PyQt6.QtWebEngineWidgets --hidden-import PyQt6.QtWebEngineCore  --icon=cronix.ico --name=Cronix cronix.py

      - name: Install NSIS
        run: choco install nsis -y

      - name: Create installer
        run: |
           & "C:\Program Files (x86)\NSIS\makensis.exe" cronix_installer.nsi

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Cronix-installer
          path: CronixSetup.exe

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Cronix-installer
          path: |
            *.exe
            !dist/Cronix.exe
